# Stubs for engineering_notation (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from engineering_notation.engineering_notation import EngNumber as EngNumber, EngUnit as EngUnit
from engineering_notation.version import __version__ as __version__
