name: Publish to pypi
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: Publish
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish
